### ISSUE TITLE
Reading data

### ISSUE THREAD

**Issue by mariobaldini** [bassages/WeatherStation#1]
Hello, 

Is your project currently working and reading the values? (commit 8ca450e392).

I tried to use it and others similar, but can not read the data from sensortag. The app runs in the device and shows the main screen, but the scan doesn't return anything and the value fields only display ---. 

Thanks

**Comment by bassages** [comment]
Hi Mario,

The app is in alfa status, has only been tested with Samsung Galaxy S4, but
sensor data should be showed.
Is bluetooth enabled on the device? Do you get a message "Successfully
connected to sensortag"?

Regards

2014-06-23 3:19 GMT+02:00 Mario Baldini notifications@github.com:

**Comment by mariobaldini** [comment]
Yes, the bluetooth is on. 

I noticed that even the official app is freezing sometimes. Bluetooth manager service crashes constantly. I'm experimenting with Moto G, Android 4.4.3 (original, no root or special configs). 

I'd like to contribute to your software if I can. I read somewhere that turning wifi off would help. This wasn't supposed to have any impact, but it did (the official app that I compiled from source started working after that. o.O). 

Since I'm completely new to Android programing, I'm having a little difficult with all the code. 

Could you point out what would be the bare minimum android code to connect to the device and read one of the sensors? (without even the graphical part, only logging to the shell and connecting using static addresses and the uuids). 

If I have this I could make some more tests and try to understand why it is not working on MotoG/Android 4.4.3).

Best regards

PS: I can read the sensors perfectly with one of the apps from the Play Store. And the device is with the latest firmware (1.5). Using iOS I also don't have any problem at all. 

The issues only rise when compiling other samples from source. The official app source freezes mostly when I try to do some rescan. But your weatherstation didn't give any sensor value in the screen. So I'd like to test the bare minimum, with static uuids (to avoid scanning) and to log data do the shell.
